language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fflores85/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fflores85/react-test npm test    

after_success:
  - docker build -t fflores85/multi-client ./client
  - docker build -t fflores85/multi-nginx ./nginx
  - docker build -t fflores85/multi-server ./server
  - docker build -t fflores85/multi-worker ./worker
  # Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fflores85/multi-client
  - docker push fflores85/multi-nginx
  - docker push fflores85/multi-server
  - docker push fflores85/multi-worker
